### ISSUE TITLE
新增主机组报错：域名参数为空

### ISSUE THREAD

**Issue by ghjacky** [qunarcorp/open_dnsdb#14]
你好，帮忙看下下边这个错误怎么解决，多谢！

**问题描述**
新增主机组，提交失败：“域名参数为空，请检查后重试”
请问这个报错是什么意思？

**环境配置**
主机组：vm01Master
主机名：vm01.inc
ip：192.168.56.11

**实际输出结果**
![image](https://user-images.githubusercontent.com/13622060/54193500-2fbb6f80-44f5-11e9-9316-4f0cc24309e6.png)

**期望输出结果**

**Comment by LostSymbol** [comment]
出现这个错误的原因是 主机名参数没有传， 不过看你操作应该没有问题，我测试添加没问题
![image](https://user-images.githubusercontent.com/24261160/54198399-5bdced80-4501-11e9-9abe-f06e0531f16c.png)

能不能用浏览器开发工具看下这条请求的传入参数  web/config/add/host_group

**Comment by ghjacky** [comment]
嗯，请求参数如下：
![image](https://user-images.githubusercontent.com/13622060/54246469-f4aa5200-456f-11e9-969a-623587a797da.png)

日志里边有报下边的错误：
前边那个错误不知道是什么意思，感觉跟这个没关系。后边那个错误说是主机名“vm01.inc”的类型不是str。具体见下边截图：
![image](https://user-images.githubusercontent.com/13622060/54246621-9631a380-4570-11e9-92c2-97fb56230427.png)

**Comment by ghjacky** [comment]
我在`dnsdb_common/library/utils.py`40行加了条日志，发现`domain_name`是`unicode`类型。。
我python环境是2.7，不是3。
![image](https://user-images.githubusercontent.com/13622060/54247741-080bec00-4575-11e9-9f6b-571b049d6680.png)

**Comment by LostSymbol** [comment]
参数是unicode应该是没问题的啊，用的basestring做判断
![image](https://user-images.githubusercontent.com/24261160/54249573-9aaf8980-457b-11e9-81f8-046cba03fe2b.png)

**Comment by ghjacky** [comment]
@LostSymbol 我下载的release里边的包:`open_dnsdb-0.2.tar.gz`，貌似用的是`isinstance(s, str)`。。
这个问题解决了，不过后续导入`named.conf`时又不行了，库里边有相应的记录，查库的时候过滤字段`group_name='Master'`，貌似`group_name`应该是`'vm01Master'`：
![image](https://user-images.githubusercontent.com/13622060/54250132-8b314000-457d-11e9-8980-127d797355d3.png)

**Comment by LostSymbol** [comment]
命令行参数：
   --group_name vm01Master

**Comment by ghjacky** [comment]
额。。不好意思，多谢！
回头继续测

**Comment by LostSymbol** [comment]
有问题欢迎交流，建议代码更新到最新哈
