### ISSUE TITLE
普通域名管理，新增域名解析后，未生效，另外发送邮件的配置里，没有邮箱密码的设置项

### ISSUE THREAD

**Issue by Atlas-2020** [qunarcorp/open_dnsdb#15]
**问题描述**
em9uZSBrZWRvdS5jb20g5pu05paw5aSx6LSlCuWOn+WboDogRmFpbGVkIHRvIGNvcHkgem9uZSBm
aWxlcyB0byB0bXBfZGlyLg==
, because: 
2019-03-14 09:52:04.560 58783 ERROR dns_updater.utils.updater_util [-] Failed to copy zone files to tmp_dir.
2019-03-14 09:52:14.589 58783 ERROR dnsdb_common.library.email_util [-] Failed to send email:From nobody Thu Mar 14 09:52:14 2019
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Subject: [DNSDB-UPDATER alarm: XYMaster]
From: =?utf-8?q?alert=40sendmail=2Eshunwang=2Ecom?=
To: =?utf-8?q?tx=2Eshi=40shunwang=2Ecom?=

**环境配置**

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by LostSymbol** [comment]
"Failed to copy zone files to tmp_dir": 这步是将所有的zone文件拷贝到tmp目录，请确认下信息：
1、etc/beta/dnsdb-updater.conf 中 zone_dir 目录是否存在, 目录下是否包含所有必要的zone文件
2、etc/beta/dnsdb-updater.conf  中 tmp_dir 下面是否存在 var/named目录（程序应该是自动创建了的）
3、手动测试下命令 `cp -Rf zone_dir/ tmp_dir/var/named/`

发送邮件的那个我看下

**Comment by LostSymbol** [comment]
邮箱密码配置

etc/beta/common.conf

[mail]
server = mail.server.corp.com
port = 25
from_addr = dnsdb@corp.com
password = xxxxxx
alert_list = ops@corp.com;opsdev@corp.com
info_list = ops@corp.com
