### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by muYoz** [qunarcorp/open_dnsdb#16]
**问题描述**

(.venv) root@bind:/home/gin/open_dnsdb# supervisorctl -c /etc/supervisord.conf
open-dnsdb                       FATAL     Exited too quickly (process log may have details)
open-dnsdb-conf-updater          FATAL     Exited too quickly (process log may have details)
open-dnsdb-zone-updater          FATAL     Exited too quickly (process log may have details)

**环境配置**
Ubuntu18.04
python3.6

**复现步骤**
1.
2.
3.

**实际输出结果**

supervisor> supervisorctl -c /etc/supervisord.conf
*** Unknown syntax: supervisorctl -c /etc/supervisord.conf
supervisor> tail -f open-dnsdb
==> Press Ctrl-C to exit <==
/usr/local/open_dnsdb/tools/with_venv.sh: line 13: /usr/local/open_dnsdb/tools//../.venv/bin/activate: No such file or directory
/usr/local/open_dnsdb/tools/with_venv.sh: line 13: /usr/local/open_dnsdb/tools//../.venv/bin/activate: No such file or directory
/usr/local/open_dnsdb/tools/with_venv.sh: line 13: /usr/local/open_dnsdb/tools//../.venv/bin/activate: No such file or directory
/usr/local/open_dnsdb/tools/with_venv.sh: line 13: /usr/local/open_dnsdb/tools//../.venv/bin/activate: No such file or directory

**期望输出结果**

**Comment by LostSymbol** [comment]
虚拟环境装好了么，项目目录下面有没有这个命令  `.venv/bin/activate`
