### ISSUE TITLE
添加zone失败，open-dnsdb-conf-updater，open-dnsdb-zone-updater启动失败

### ISSUE THREAD

**Issue by GN01** [qunarcorp/open_dnsdb#17]
**问题描述**
添加zone失败，
open-dnsdb-conf-updater、open-dnsdb-zone-updater启动失败

**环境配置**
CentOS Linux release 7.6.1810 (Core) 
Linux bind 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
BIND 9.14.0 (Stable Release) <id:90df20a>

**复现步骤**
1.Successfully built Flask-Login httplib2 SQLAlchemy fixture alembic pyrsistent PyYAML Mako wrapt
Installing collected packages: concurrent-log-handler, click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, Flask, Flask-Login, SQLAlchemy, Flask-SQLAlchemy, Mako, python-editor, six, python-dateutil, alembic, Flask-Migrate, pytz, aniso8601, Flask-RESTful, httplib2, attrs, pyrsistent, jsonschema, rfc3986, babel, oslo.i18n, netaddr, stevedore, PyYAML, wrapt, debtcollector, chardet, urllib3, certifi, idna, requests, oslo.config, multiping, imagesize, pyparsing, packaging, sphinxcontrib-websupport, docutils, alabaster, snowballstemmer, Pygments, Sphinx, sphinx-rtd-theme, gunicorn, monotonic, dnspython, greenlet, eventlet, python-mimeparse, linecache2, traceback2, argparse, unittest2, fixtures, extras, testtools, WebOb, soupsieve, beautifulsoup4, waitress, WebTest, virtualenv, filelock, pluggy, toml, py, tox, fixture, mock
Successfully installed Flask-1.0.2 Flask-Login-0.4.1 Flask-Migrate-2.4.0 Flask-RESTful-0.3.7 Flask-SQLAlchemy-2.3.2 Jinja2-2.10 Mako-1.0.8 MarkupSafe-1.1.1 PyYAML-5.1 Pygments-2.3.1 SQLAlchemy-1.2.18 Sphinx-1.8.4 WebOb-1.8.5 WebTest-2.0.33 Werkzeug-0.15.2 alabaster-0.7.12 alembic-1.0.8 aniso8601-6.0.0 argparse-1.4.0 attrs-19.1.0 babel-2.6.0 beautifulsoup4-4.7.1 certifi-2019.3.9 chardet-3.0.4 click-7.0 concurrent-log-handler-0.9.12 debtcollector-1.21.0 dnspython-1.16.0 docutils-0.14 eventlet-0.24.1 extras-1.0.0 filelock-3.0.10 fixture-1.5.11 fixtures-3.0.0 greenlet-0.4.15 gunicorn-19.9.0 httplib2-0.12.1 idna-2.8 imagesize-1.1.0 itsdangerous-1.1.0 jsonschema-3.0.1 linecache2-1.0.0 mock-2.0.0 monotonic-1.5 multiping-1.1.2 netaddr-0.7.19 oslo.config-6.8.1 oslo.i18n-3.23.1 packaging-19.0 pluggy-0.9.0 py-1.8.0 pyparsing-2.3.1 pyrsistent-0.14.11 python-dateutil-2.8.0 python-editor-1.0.4 python-mimeparse-1.6.0 pytz-2018.9 requests-2.21.0 rfc3986-1.2.0 six-1.12.0 snowballstemmer-1.2.1 soupsieve-1.9 sphinx-rtd-theme-0.4.3 sphinxcontrib-websupport-1.1.0 stevedore-1.30.1 testtools-2.3.0 toml-0.10.0 tox-3.8.6 traceback2-1.4.0 unittest2-1.1.0 urllib3-1.24.1 virtualenv-16.4.3 waitress-1.2.1 wrapt-1.11.1

2.Installing collected packages: concurrent-log-handler, click, itsdangerous, Werkzeug, MarkupSafe, Jinja2, Flask, Flask-Login, SQLAlchemy, Flask-SQLAlchemy, python-editor, six, python-dateutil, Mako, alembic, Flask-Migrate, pytz, aniso8601, Flask-RESTful, httplib2, pyrsistent, attrs, jsonschema, pbr, babel, oslo.i18n, PyYAML, stevedore, netaddr, urllib3, chardet, certifi, idna, requests, wrapt, debtcollector, rfc3986, oslo.config, multiping, sphinxcontrib-websupport, snowballstemmer, Pygments, docutils, alabaster, pyparsing, packaging, imagesize, Sphinx, sphinx-rtd-theme, gunicorn, dnspython, greenlet, monotonic, eventlet
Successfully installed Flask-1.0.2 Flask-Login-0.4.1 Flask-Migrate-2.4.0 Flask-RESTful-0.3.7 Flask-SQLAlchemy-2.3.2 Jinja2-2.10 Mako-1.0.8 MarkupSafe-1.1.1 PyYAML-5.1 Pygments-2.3.1 SQLAlchemy-1.2.18 Sphinx-1.8.4 Werkzeug-0.15.2 alabaster-0.7.12 alembic-1.0.8 aniso8601-6.0.0 attrs-19.1.0 babel-2.6.0 certifi-2019.3.9 chardet-3.0.4 click-7.0 concurrent-log-handler-0.9.12 debtcollector-1.21.0 dnspython-1.16.0 docutils-0.14 eventlet-0.24.1 greenlet-0.4.15 gunicorn-19.9.0 httplib2-0.12.1 idna-2.8 imagesize-1.1.0 itsdangerous-1.1.0 jsonschema-3.0.1 monotonic-1.5 multiping-1.1.2 netaddr-0.7.19 oslo.config-6.8.1 oslo.i18n-3.23.1 packaging-19.0 pbr-5.1.3 pyparsing-2.3.1 pyrsistent-0.14.11 python-dateutil-2.8.0 python-editor-1.0.4 pytz-2018.9 requests-2.21.0 rfc3986-1.2.0 six-1.12.0 snowballstemmer-1.2.1 sphinx-rtd-theme-0.4.3 sphinxcontrib-websupport-1.1.0 stevedore-1.30.1 urllib3-1.24.1 wrapt-1.11.1

3.Installing dnsdb script to /usr/local/open_dnsdb/.venv/bin
Installing dnsdb-conf-updater script to /usr/local/open_dnsdb/.venv/bin
Installing dnsdb-zone-updater script to /usr/local/open_dnsdb/.venv/bin

**实际输出结果**
(.venv) [root@bind open_dnsdb]# supervisorctl -c /etc/supervisord.conf
open-dnsdb                       RUNNING   pid 10236, uptime 0:00:12
open-dnsdb-conf-updater          FATAL     Exited too quickly (process log may have details)
open-dnsdb-zone-updater          FATAL     Exited too quickly (process log may have details)
supervisor> tail -f open-dnsdb
==> Press Ctrl-C to exit <==
ator
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators     return resp(data=func(*kargs, **kwargs), is_json=is_json)
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb/view/api/__init__.py", line 34, in get_host_group
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators     return HostGroupConfDal.get_group_by_ip(host_ip)
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/dal/host_group_conf.py", line 51, in get_group_by_ip
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators     raise BadParam('No such ip record: %s' % host_ip, msg_ch=u'请先将ip %s 写入数据库' % host_ip)
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators dnsdb_common.library.exception.BadParam: No such ip record: 172.16.16.214
2019-04-04 16:15:20.361 10261 TRACE dnsdb_common.library.decorators 
[2019-04-04 16:15:20 +0800] [10261] [DEBUG] Closing connection.

**期望输出结果**

**Comment by LostSymbol** [comment]
需要先在dnsdb里添加主机 https://github.com/qunarcorp/open_dnsdb/wiki/confManage

**Comment by GN01** [comment]
![image](https://user-images.githubusercontent.com/30264589/55544571-f2b25980-56fd-11e9-92df-7041b231daac.png)
![image](https://user-images.githubusercontent.com/30264589/55544670-24c3bb80-56fe-11e9-852f-4c9b9d50a6f6.png)

已添加过主机但是没有获取MD5
操作日志也没返回

**Comment by LostSymbol** [comment]
这个md5是named.conf的md5, 需要手动导入的, 麻烦先看下操作文档 https://github.com/qunarcorp/open_dnsdb/wiki/startUpdater
