### ISSUE TITLE
邮箱密码没有地方设置

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#19]
; 邮件相关配置
[mail]
server = mail.server.corp.com
port = 25
from_addr = dnsdb@corp.com
alert_list = ops@corp.com;opsdev@corp.com
info_list = ops@corp.com;opsdev@corp.com

**Comment by LostSymbol** [comment]
代码已更新，支持邮箱密码配置：
etc/beta/common.conf
```
[mail]
server = mail.server.corp.com
port = 25
from_addr = dnsdb@corp.com
password = xxxxxx
alert_list = ops@corp.com;opsdev@corp.com
info_list = ops@corp.com
```
