### ISSUE TITLE
supervisor启动失败

### ISSUE THREAD

**Issue by shuish0071** [qunarcorp/open_dnsdb#2]
**问题描述**
部署的时候，执行【cp etc/beta/supervisor-dnsdb.conf /etc/supervisor/conf.d/open-dnsdb.conf】
再执行【supervisord -c /etc/supervisord.conf】失败
**环境配置**
centos 7.5，python2.7

问题原因：
etc/beta/supervisor-dnsdb.conf 文件中将目录【open_dnsdb】改成了【open-dnsdb】
解决：改回到【open_dnsdb】

**Comment by shuish0071** [comment]
顺便问一下有没有怎么使用opendns的文档，或者有没有QQ群等更多交流的方式？

环境：centos 7.5 python2.7，安装完编译的基础包
以下是我部署成功的完整步骤，懒得做自动化脚本了，给其他人参考下

git clone https://github.com/qunarcorp/open_dnsdb.git

yum install python-pip -y

pip python -m pip install --upgrade pip

yum install -y python-virtualenv

python tools/install_venv.py

source /opt/open_dnsdb/.venv/bin/activate

export FLASK_APP=dnsdb_command.py

export FLASK_ENV=beta

source .venv/bin/activate

export FLASK_APP=dnsdb_command.py
export FLASK_ENV=beta

mkdir -p /opt/open_dnsdb/data && touch dnsdb.db

vim /opt/open_dnsdb/etc/beta/common.conf

	connection=sqlite:////opt/open_dnsdb/data/dnsdb.db

flask deploy 

/opt/open_dnsdb/tools/with_venv.sh python setup.py install

yum install supervisor -y

vim /etc/supervisord.conf 
	[include]
	files = supervisord.d/*.conf
	
cp /opt/open_dnsdb/etc/beta/supervisor-dnsdb.conf /etc/supervisor/conf.d/open-dnsdb.conf

mkdir /var/log/open-dnsdb/

vim /etc/supervisord.d/supervisor-dnsdb.conf 
[program:open-dnsdb]
directory=/opt/open_dnsdb/
command=/opt/open_dnsdb/tools/with_venv.sh dnsdb beta dnsdb
autostart=True         ;; 是否开机自动启动
autorestart=True       ;; 是否挂了自动重启
redirect_stderr=True    ;; 是否把 stderr 定向到 stdout
stopasgroup=True

supervisord -c /etc/supervisord.conf

登陆网站【ip:9001】	
用户名/密码【test/123456】

**Comment by shuish0071** [comment]
顺便问一下有没有怎么使用opendns的文档，或者有没有QQ群等更多交流的方式？

环境：centos 7.5 python2.7，安装完编译的基础包
以下是我部署成功的完整步骤，懒得做自动化脚本了，给其他人参考下

git clone https://github.com/qunarcorp/open_dnsdb.git

yum install python-pip -y

pip python -m pip install --upgrade pip

yum install -y python-virtualenv

python tools/install_venv.py

source /opt/open_dnsdb/.venv/bin/activate

export FLASK_APP=dnsdb_command.py

export FLASK_ENV=beta

source .venv/bin/activate

export FLASK_APP=dnsdb_command.py
export FLASK_ENV=beta

mkdir -p /opt/open_dnsdb/data && touch dnsdb.db

vim /opt/open_dnsdb/etc/beta/common.conf

	connection=sqlite:////opt/open_dnsdb/data/dnsdb.db

flask deploy 

/opt/open_dnsdb/tools/with_venv.sh python setup.py install

yum install supervisor -y

vim /etc/supervisord.conf 
	[include]
	files = supervisord.d/*.conf
	
cp /opt/open_dnsdb/etc/beta/supervisor-dnsdb.conf /etc/supervisor/conf.d/open-dnsdb.conf

mkdir /var/log/open-dnsdb/

vim /etc/supervisord.d/supervisor-dnsdb.conf 
[program:open-dnsdb]
directory=/opt/open_dnsdb/
command=/opt/open_dnsdb/tools/with_venv.sh dnsdb beta dnsdb
autostart=True         ;; 是否开机自动启动
autorestart=True       ;; 是否挂了自动重启
redirect_stderr=True    ;; 是否把 stderr 定向到 stdout
stopasgroup=True

supervisord -c /etc/supervisord.conf

登陆网站【ip:9001】	
用户名/密码【test/123456】

**Comment by LostSymbol** [comment]
配置文件已经修改

使用文档会尽快更新, 谢谢支持
