### ISSUE TITLE
zone删除不彻底

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#20]
**问题描述**
zone删除不彻底，页面上删除zone后，配置文件 /usr/local/open_dnsdb/tmp/var/named/chroot/etc/Master 和 Master_used中还存在

**Comment by wss434631143** [comment]
找到问题了，是我修改了updater的端口，然后update了一下代码，common.conf里链接updater的端口被改回去了

**Comment by LostSymbol** [comment]
ok, issut关闭了哈
