### ISSUE TITLE
bug:IE浏览器点击“”操作日志“”异常

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#21]
**问题描述**
在IE浏览器中访问http://localhost:9001，点击“操作日志”报错==》异常 状态码:undefined
在chrome类浏览器中访问正常。
![image](https://user-images.githubusercontent.com/6138576/55780104-c02ba680-5ad9-11e9-893c-3cd2a7fa20d8.png)

**Comment by LostSymbol** [comment]
暂时没做浏览器兼容，目前确定可支持的浏览器: chrome, firefox
