### ISSUE TITLE
bug:chrome浏览器下，多个域名，首页系统概览中域名显示不全

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#22]
**问题描述**

bug:chrome浏览器下，多个域名，首页系统概览中域名显示不全，如下图所示：

![image](https://user-images.githubusercontent.com/6138576/55780438-7d1e0300-5ada-11e9-905c-6d5cd07fdc07.png)
![image](https://user-images.githubusercontent.com/6138576/55780461-8909c500-5ada-11e9-9aa6-dba49ab62e8f.png)

**Comment by LostSymbol** [comment]
已修改
