### ISSUE TITLE
bug:/var/log目录下日志文件夹有两个open_dnsdb和open-dnsdb

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#24]
**问题描述**
/var/log目录下日志文件夹有两个open_dnsdb和open-dnsdb，希望统一为一个，另外updater的日志并没有输出到/var/log/open_dnsdb中。
![image](https://user-images.githubusercontent.com/6138576/55781011-ca4ea480-5adb-11e9-9090-822839a40854.png)
![image](https://user-images.githubusercontent.com/6138576/55781038-d89cc080-5adb-11e9-8f3c-5a63b0e8cbd4.png)

**Comment by LostSymbol** [comment]
1、看一下这两个文件夹的创建时间，应该有一个是更新邮箱密码设置代码之后创建的，为了和dnsdb保持统一，我改了配置文件中的log文件夹，所以这个问题忽略

2、updater的日志：通过supervisor启动，所以日志是supervisor管理的，需要统一的话改下supervisor的配置文件/etc/supervisord.conf : 
```
[supervisord]
childlogdir=/var/log/open_dnsdb         ; 'AUTO' child log dir, default $TEMP
```

如果没问题的话，麻烦把issue关掉，谢谢
