### ISSUE TITLE
启动open-dnsdb-conf-updater失败报错

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#25]
**问题描述**
启动open-dnsdb-conf-updater时报错如下：
2019-04-09 16:28:47.571 3988 TRACE dnsdb_updater_www requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9001): Max retries exceeded with url: /api/get/host_group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8fa1a0d6a0>: Failed to establish a new connection: [Errno 111] Connection refused',))

主机组这些是添加过的，之前也启动成功过，之前是误打误撞修改了hosts反复测试，结果启动成功了。

这次我把之前修改的hosts(localhost解析到服务器真实IP)这条解析记录去掉，然后重新reload,发现启动失败了

看上面的日志发现是访问不了 localhost:9001这个借口，于是本地用curl测试：
![image](https://user-images.githubusercontent.com/6138576/55787768-94b0b800-5ae9-11e9-9690-6b2b742b8258.png)

发现locallocalhost是正常可以解析到127.0.0.1的，但是访问9001端口却被拒绝，然后用127.0.0.1测试正常能访问
![image](https://user-images.githubusercontent.com/6138576/55787429-d1c87a80-5ae8-11e9-8e24-b2f7113baa67.png)

确定是这个原因导致open-dnsdb-conf-updater失败报错的。

会不会和配置文件中
/usr/local/open_dnsdb/etc/beta/dnsdb-updater.conf
allow_ip = 127.0.0.1 这个配置项有关系

**Comment by LostSymbol** [comment]
和这个配置项应该无关，测试环境这个配置项其实没有真正起作用

你的思路应该是对的，应该和localhost的解析有关，我之前没考虑会有这个问题。介意贴一下不能正常访问情况下的/etc/host文件么

**Comment by wss434631143** [comment]
就默认的 /etc/hosts文件
![image](https://user-images.githubusercontent.com/6138576/55789812-9b412e80-5aed-11e9-939d-fb1aafd59658.png)
然后我手动把这两行注释掉，手动添加一条记录就可以了，很奇怪
![image](https://user-images.githubusercontent.com/6138576/55789842-b4e27600-5aed-11e9-9c7f-11bce6cd49d7.png)
![image](https://user-images.githubusercontent.com/6138576/55789871-c592ec00-5aed-11e9-981c-10941b8470ea.png)

**Comment by LostSymbol** [comment]
默认情况下不可以么

**Comment by wss434631143** [comment]
默认情况下不可以，访问接口会报拒绝
![image](https://user-images.githubusercontent.com/6138576/55790204-700b0f00-5aee-11e9-9c4c-5d37be83b1ad.png)
然后导致open-dnsdb-conf-updater启动失败

**Comment by wss434631143** [comment]
我觉得是不是应该把/usr/local/open_dnsdb/etc/beta/common.conf配置项
[api]
dnsdbapi_url=http://localhost:9001/api
dnsupdater_port = 9000
改为
[api]
dnsdbapi_url=http://127.0.0.1:9001/api
dnsupdater_port = 9000

这样可能不会导致那么多人启动出错

**Comment by LostSymbol** [comment]
嗯， 好的建议，多谢
