### ISSUE TITLE
执行 tools/with_venv.sh python setup.py 报错

### ISSUE THREAD

**Issue by lileih** [qunarcorp/open_dnsdb#33]
**问题描述**
执行 tools/with_venv.sh python setup.py 报错

error in setup command: Error parsing /opt/open_dnsdb/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name dnsdb was given, but was not able to be found.

**环境配置**
x86_64  python3.6.8  pip 19.1.1

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by kenkong2019** [comment]
Hi 这个问题怎么解决的？
