### ISSUE TITLE
启动open-dnsdb-conf-updater和open-dnsdb-zone-updater报错

### ISSUE THREAD

**Issue by lileih** [qunarcorp/open_dnsdb#34]
**问题描述**
你好，启动open-dnsdb-zone-updater和open-dnsdb-zone-updater是会打印以下报错：
 TRACE dnsdb_updater_www     raise ConnectionError(e, request=request)
 TRACE dnsdb_updater_www ConnectionError: HTTPConnectionPool(host='localhost', port=9001): Max retries exceeded with url: /api/get/host_group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faebe63ae50>: Failed to establish a new connection: [Errno 111] Connection refused',))
 TRACE dnsdb_updater_www
 ERROR dns_updater.app [-] This host belong to host group DNSMaster

------------------------------------------------------------------------------
 TRACE dnsdb_upater_zone ConnectionError: HTTPConnectionPool(host='localhost', port=9001): Max retries exceeded with url: /api/get/host_group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9d9649fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
TRACE dnsdb_upater_zone
 ERROR dns_updater.updater [-] Host belong to group: DNSMaster
控制台一直显示
![image](https://user-images.githubusercontent.com/10669788/61297537-039b5c80-a80f-11e9-9209-78a9c2d6664e.png)

open-dnsdb-stdout日志一直有访问接口输出
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /api/get/update_zones
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /api/get/update_zones
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /api/get/update_zones
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection. 
[DEBUG] GET /web/preview/list/operation_log
[DEBUG] Closing connection.

排查过程
1）我通过curl  localhost   和 curl 127.0.0.1  都没有问题
2）修改下面配置内容localhost为127.0.0.1 依然不行
[api]
dnsdbapi_url=http://localhost:9001/api
dnsupdater_port = 9000

请问这里的报错跟哪里有关呢

**环境配置**
cenos7.5
python2.7.13
pip 19.1.1

**Comment by LostSymbol** [comment]
这个不好判断，curl 的是全路径么，另外master支持的是python3

**Comment by lileih** [comment]
经过验证这个报错其实不影响服务正常使用，谢谢。
