### ISSUE TITLE
新加域名不展示

### ISSUE THREAD

**Issue by lileih** [qunarcorp/open_dnsdb#35]
**问题描述**
你好，我搭建好平台在测试过程发现一些问题
1）新加域名解析不显示，必须在搜索框搜索才能显示。
![image](https://user-images.githubusercontent.com/10669788/61364547-a9ef6c80-a8b8-11e9-8dd4-9b4d6964b0c1.png)
如上图。
 
**环境配置**
centos7_x86_64
python3.6.8
pip19.1.1

**Comment by LostSymbol** [comment]
不是很理解新增域名不显示是什么意思？是指新增域名成功之后没有显示添加的域名么

**Comment by lileih** [comment]
新加域名web页面端不会显示出来，要搜索后才能显示，不过也不影响正常使用，只是查询的时候需要搜索。
