### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by kratos-wq** [qunarcorp/open_dnsdb#41]
**问题描述**
supervisor服务启动成功，进入客户端无进程；后单独执行启动脚本的命令报错：
open_dnsdb/tools/with_venv.sh: line 14: dnsdb: command not found

**环境配置**
python3，Vscode

**复现步骤**
1.执行supervisorctl -c /etc/supervisord.conf，无进程
2.执行open_dnsdb/tools/with_venv.sh dnsdb beta dnsdb，报错dnsdb: command not found

**实际输出结果**
如上

**期望输出结果**
服务启动成功

**Comment by LostSymbol** [comment]
确定执行过这条命了了么 tools/with_venv.sh python setup.py install

**Comment by kratos-wq** [comment]
执行过了

**Comment by kratos-wq** [comment]
换了个python2版本的可以了，可能是本地两个python版本的问题，多谢！
