### ISSUE TITLE
Undefined names in __all__

### ISSUE THREAD

**Issue by cclauss** [qunarcorp/open_dnsdb#5]
[flake8](http://flake8.pycqa.org) testing of https://github.com/qunarcorp/open_dnsdb on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./dnsdb_common/library/utils.py:23:1: F822 undefined name 'is_subnet_public' in __all__
__all__ = (
^
./dnsdb_common/library/utils.py:23:1: F822 undefined name 'load_config_option' in __all__
__all__ = (
^
./dnsdb_common/library/utils.py:23:1: F822 undefined name 'is_valid_ip_bysocketis_string' in __all__
__all__ = (
^
3     F822 undefined name 'is_subnet_public' in __all__
3
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by LostSymbol** [comment]
Fixed that. Thank you very much!
