### ISSUE TITLE
初始化环境失败

### ISSUE THREAD

**Issue by charles-liming** [qunarcorp/open_dnsdb#6]
**问题描述**
[root@YZSJHL82-215 open_dnsdb]# python tools/install_venv.py
venv already exists...
Installing dependencies with pip (this can take a while)...
Requirement already up-to-date: pip>=1.4 in ./.venv/lib/python3.6/site-packages (19.0.1)
Requirement already up-to-date: setuptools in ./.venv/lib/python3.6/site-packages (40.6.3)
Requirement already up-to-date: pbr in ./.venv/lib/python3.6/site-packages (5.1.1)
Collecting ConcurrentLogHandler==0.9.1 (from -r /data/open_dnsdb/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fd/e5/0dc4f256bcc6484d454006b02f33263b20f762a433741b29d53875e0d763/ConcurrentLogHandler-0.9.1.tar.gz
▽ollecting Flask-RESTful==0.3.6 (from -r /data/open_dnsdb/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/47/08/89cf8594735392cd71752f7cf159fa63765eac3e11b0da4324cdfeaea137/Flask_RESTful-0.3.6-py2.py3-none-any.whl
Collecting Flask==1.0.2 (from -r /data/open_dnsdb/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting Flask-SQLAlchemy==2.3.2 (from -r /data/open_dnsdb/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a1/44/294fb7f6bf49cc7224417cd0637018db9fee0729b4fe166e43e2bbb1f1c8/Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Collecting httplib2==0.9.1 (from -r /data/open_dnsdb/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/38/9c/cd76fde3a74d36a0317422dee019ae5f73ce27e62d817ca003e018d9f9d8/httplib2-0.9.1.tar.gz
Collecting jsonschema==2.6.0 (from -r /data/open_dnsdb/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting oslo.config==1.4.0 (from -r /data/open_dnsdb/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/4d/89/51a21caa79ccfba7b0c879ff073e35fe0e3783cc120e69fe84943a87bc35/oslo.config-1.4.0-py2.py3-none-any.whl
Collecting ping==0.2 (from -r /data/open_dnsdb/requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/03/ac/9a3f332f8d7d27cd8929922b2e225842c1623760364b37fc79dc0f65e77d/ping-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cxlw7p7y/ping/setup.py", line 23, in <module>
        from ping import __version__
      File "/tmp/pip-install-cxlw7p7y/ping/ping.py", line 196
        except socket.error, (errno, msg):
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cxlw7p7y/ping/
Command "tools/with_venv.sh pip install --upgrade -r /data/open_dnsdb/requirements.txt -r /data/open_dnsdb/test-requirements.txt" failed.
None
[root@YZSJHL82-215 open_dnsdb]# cd /tmp

**环境配置**
centos7   py3.6   pip19.01 

**复现步骤**
1.python tools/install_venv.py
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by LostSymbol** [comment]
python版本切到2.7试试

**Comment by Steelki** [comment]
[root@YZSJHL82-215 open_dnsdb]# python2 tools/install_venv.py
venv already exists...
Installing dependencies with pip (this can take a while)...
Requirement already up-to-date: pip>=1.4 in ./.venv/lib/python3.6/site-packages (19.0.1)
Requirement already up-to-date: setuptools in ./.venv/lib/python3.6/site-packages (40.6.3)
Requirement already up-to-date: pbr in ./.venv/lib/python3.6/site-packages (5.1.1)
Collecting ConcurrentLogHandler==0.9.1 (from -r /data/open_dnsdb/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fd/e5/0dc4f256bcc6484d454006b02f33263b20f762a433741b29d53875e0d763/ConcurrentLogHandler-0.9.1.tar.gz
Collecting Flask-RESTful==0.3.6 (from -r /data/open_dnsdb/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/47/08/89cf8594735392cd71752f7cf159fa63765eac3e11b0da4324cdfeaea137/Flask_RESTful-0.3.6-py2.py3-none-any.whl
Collecting Flask==1.0.2 (from -r /data/open_dnsdb/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting Flask-SQLAlchemy==2.3.2 (from -r /data/open_dnsdb/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a1/44/294fb7f6bf49cc7224417cd0637018db9fee0729b4fe166e43e2bbb1f1c8/Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Collecting httplib2==0.9.1 (from -r /data/open_dnsdb/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/38/9c/cd76fde3a74d36a0317422dee019ae5f73ce27e62d817ca003e018d9f9d8/httplib2-0.9.1.tar.gz
Collecting jsonschema==2.6.0 (from -r /data/open_dnsdb/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting oslo.config==1.4.0 (from -r /data/open_dnsdb/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/4d/89/51a21caa79ccfba7b0c879ff073e35fe0e3783cc120e69fe84943a87bc35/oslo.config-1.4.0-py2.py3-none-any.whl
Collecting ping==0.2 (from -r /data/open_dnsdb/requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/03/ac/9a3f332f8d7d27cd8929922b2e225842c1623760364b37fc79dc0f65e77d/ping-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uvpxjrwd/ping/setup.py", line 23, in <module>
        from ping import __version__
      File "/tmp/pip-install-uvpxjrwd/ping/ping.py", line 196
        except socket.error, (errno, msg):
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-uvpxjrwd/ping/
Command "tools/with_venv.sh pip install --upgrade -r /data/open_dnsdb/requirements.txt -r /data/open_dnsdb/test-requirements.txt" failed.
None
[root@YZSJHL82-215 open_dnsdb]# pip -V  
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
[root@YZSJHL82-215 open_dnsdb]# python2  -V
Python 2.7.5
[root@YZSJHL82-215 open_dnsdb]# python  -V
Python 2.7.5

**Comment by Steelki** [comment]
感觉这个项目就没有声明环境啊，提供一下环境信息把

**Comment by LostSymbol** [comment]
我这儿的测试环境信息：
Python 2.7.13  
pip 18.1
安装没有问题，你试下

**Comment by Steelki** [comment]
好的
