### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by dingbb** [qunarcorp/open_dnsdb#7]
**问题描述**

[root@k8s-node1 local]# supervisorctl -c /etc/supervisord.conf
open-dnsdb                       FATAL     Exited too quickly (process log may have details)
supervisor>

**环境配置**
centos7.5
python2.7 
pip 19

**复现步骤**
1.
2.
3.

**实际输出结果**

[root@k8s-node1 local]# supervisorctl -c /etc/supervisord.conf
open-dnsdb                       FATAL     Exited too quickly (process log may have details)
supervisor>
**期望输出结果**

**Comment by LostSymbol** [comment]
```
$ supervisorctl -c /etc/supervisord.conf
supervisor> tail -f open-dnsdb
```
看一下错误信息
